{
 "title": "Algemeen dashboard beheer",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "group",
    "label": "Naam",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},group)"
    }
   },
   {
    "name": "subgroup",
    "label": "Type",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", group=~\"$group\"},subgroup)"
    }
   },
   {
    "name": "instance",
    "label": "Link",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\"},instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"apiserver\"},cluster)"
    }
   },
   {
    "name": "instance1",
    "label": "instance1",
    "query": {
     "query": "label_values(up{job=~\"apiserver\", cluster=~\"$cluster\"},instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\"},namespace)"
    }
   },
   {
    "name": "cluster1",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\"},namespace)"
    }
   },
   {
    "name": "volume",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=~\"$cluster1\", job=~\"kubelet\", metrics_path=~\"/metrics\", namespace=~\"$namespace\"},persistentvolumeclaim)"
    }
   },
   { "name": "job1", "query": { "query": "label_values(job)" } },
   {
    "name": "k8s_version",
    "query": {
     "query": "label_values(kube_node_info,kubelet_version)"
    }
   },
   { "name": "Versie_dashboard", "query": "1.1" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "HTTP status code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Status code",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{job=~'$job', subgroup=~\"$subgroup\", group=~\"$group\",instance=~'$instance'})",
     "legendFormat": "http status {{ value }}"
    }
   ]
  },
  {
   "title": "probe success / failure",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " count_values('value',probe_success{job=~'$job', subgroup=~\"$subgroup\", group=~\"$group\",instance=~'$instance'})",
     "legendFormat": "{{ value }}"
    }
   ]
  },
  {
   "title": "probe success / failure",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (probe_http_status_code{job=~'$job', subgroup=~\"$subgroup\", group=~\"$group\",instance=~'$instance'} - 0 == 200)",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "sum by (instance) (probe_http_status_code{job=~'$job', subgroup=~\"$subgroup\", group=~\"$group\",instance=~'$instance'} - 0 != 200)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Summary of alerts status",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{severity=\"critical\"}) or vector(0)",
     "legendFormat": "Critical alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{severity=\"warning\"}) OR vector(0)",
     "legendFormat": "Warning alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{severity=\"info\"}) OR vector(0)",
     "legendFormat": "Info alert"
    }
   ]
  },
  { "title": "Versies componenten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Grafana versie",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "grafana_build_info{job=~\"$job1\"}"
    }
   ]
  },
  {
   "title": "Prometheus Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info {cluster=~\"$cluster\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Prometheus Operator Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "prometheus_operator_build_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Grafana Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "grafana_build_info{cluster=~\"$cluster\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Node Ubuntu OS Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_os_version", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kubernetes cluster version",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 25 },
   "options": {
    "content": "<div class=\"text-center\">\n  <img style=\"height:80px\" src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Kubernetes_logo_without_workmark.svg/1200px-Kubernetes_logo_without_workmark.svg.png\">\n  <h2 style=\"padding-top:20px\">$k8s_version</h2>\n</div>"
   },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  { "title": "Beschikbaarheid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "API Server - Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"apiserver\", cluster=~\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Availability (30d) > 99.000%",
   "type": "stat",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Write Availability (30d)",
   "type": "stat",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"write\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Read Availability (30d)",
   "type": "stat",
   "description": "How many percent of read requests (LIST,GET) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"read\", cluster=\"$cluster\"}"
    }
   ]
  },
  { "title": "SSL certificaten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Globale status SSL certificaten",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\", group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'} - 0 "
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'} - 0"
    },
    {
     "expr": "probe_http_ssl{job=\"$job\", group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=\"$job\",group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'}-time()"
    }
   ]
  },
  {
   "title": "SSL status",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\",group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\",instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{group=~\"$group|flink_taskmanager|ignite|gateway|mysql|nacos|nginx|streamtau|uumsx\",subgroup=~\"$subgroup\",job=~\"$job$\"}",
     "legendFormat": "{{ group }}-{{ instance }}"
    }
   ]
  }
 ]
}