{
 "title": "Certificaat",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   },
   {
    "name": "group",
    "label": "groep",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},group)"
    }
   },
   {
    "name": "target",
    "label": "url",
    "query": {
     "query": "label_values(probe_success{group=~\"$group\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP status code",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Certificate validity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{instance=\"$target\"} - time()) / (60*60*24)"
    }
   ]
  },
  {
   "title": "TLS version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "probe_tls_version_info{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "DNS lookup time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_dns_lookup_time_seconds{instance=\"$target\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "HTTP version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Redirect(s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_redirects{instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\",instance=\"$target\"}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$job\",instance=\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=~\"$job\",instance=\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{job=\"$job\",instance=\"$target\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "HTTP probe duration / status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$target\",job=~\"$job\"}",
     "legendFormat": "duration"
    },
    {
     "expr": "probe_http_status_code{instance=\"$target\"} == 200",
     "legendFormat": "status code"
    },
    {
     "expr": "probe_http_status_code{instance=\"$target\"} != 200",
     "legendFormat": "invalid status code"
    }
   ]
  },
  {
   "title": "ICMP probe duration / failure",
   "type": "graph",
   "description": "Display only ICMP failures",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"$target\",job=~\"$job\"}",
     "legendFormat": "duration"
    },
    {
     "expr": "probe_success{job=~\"$job\",instance=\"$target\"} == 0",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "HTTP probe (by phase)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}