{
 "title": "Logging",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "app",
    "query": {}
   },
   {
    "name": "pod",
    "query": {}
   },
   {
    "name": "container",
    "query": {}
   },
   { "name": "search" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Error/warning componenten",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error/warning Loki",
     "type": "logs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "{app=\"loki\"} | logfmt | level=\"warning\" or level=\"error\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error/warning Promtail",
     "type": "logs",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "{app=\"grafana\"} | logfmt | level=\"warning\" or level=\"error\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error/warning Prometheus",
     "type": "logs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "{app=\"prometheus\"} | logfmt | level=\"warning\" or level=\"error\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error/warning Promtail",
     "type": "logs",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "{app=\"promtail\"} | logfmt | level=\"warning\" or level=\"error\" |~ \"$search\""
      }
     ]
    },
    {
     "title": "Error/warning Ingress app gateway",
     "type": "logs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "{app=\"ingress-appgw\"} | logfmt | level=\"warning\" or level=\"error\" |~ \"$search\""
      }
     ]
    }
   ]
  },
  {
   "title": "Totale logs error",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time({namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\", stream=\"stderr\"} |= `` [$__auto])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Totale logs output",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "count_over_time({namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\", stream=\"stdout\"} |= `` [$__auto])",
     "legendFormat": "{{app}}"
    }
   ]
  },
  { "title": "Alle logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"$search\""
    }
   ]
  },
  { "title": "Succesvolle logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "STDOUT",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\", stream=\"stdout\"}\r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"$search\""
    }
   ]
  },
  { "title": "Error logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "STDERR",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\", stream=\"stderr\"}\r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"$search\""
    }
   ]
  },
  { "title": "HTTP 2x (Success)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Requests met HTTP 2x code",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*`  \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"HTTP/1.1\\\" 2\\\\d{2}\" \r\n|~ \"$search\""
    }
   ]
  },
  {
   "title": "Requests zonder alle HTTP 2x codes",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n!~ \"HTTP/1.1 2\\\\d{2}\" !~ \"HTTP/1.1\\\" 2\\\\d{2}\" \r\n|~ `$search`"
    }
   ]
  },
  {
   "title": "Requests zonder HTTP 200 2 codes",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n!~ \"HTTP/1.1 20\\\\d{1}\" !~\"GET /_health/ HTTP/1.1\\\" 200 2\" \r\n|~ `$search`"
    }
   ]
  },
  { "title": "HTTP 3x (Redirection)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Requests met HTTP 3x codes",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", app=~\"$app\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"HTTP/1.1\\\" 3\\\\d{2}\" \r\n|~ `$search`"
    }
   ]
  },
  { "title": "HTTP 4x (Client errors)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Requests met HTTP 4x codes",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"HTTP/1.1 4\\\\d{2}\" \r\n|~ `$search`"
    }
   ]
  },
  { "title": "HTTP 5x (Server errors)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Requests met HTTP 5x codes",
   "type": "logs",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", app=~\"$app\", pod=~\"$pod\", container=~\"$container\"} \r\n| regexp `.*HTTP\\/1.1\" (?P<http_code>\\d+) \\d+.*` \r\n| regexp `.*(?P<public_ip>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b) .*`\r\n| regexp `.*(?P<ip_address>\\b\\d{1,3}(?:\\.\\d{1,3}){3}\\b):(?P<port>\\d+).*`\r\n| regexp `.*\"(?P<http_method>\\b(?:GET|PUT|POST|DELETE|PATCH)\\b) (?P<url>\\/[^\"]*) HTTP/1.1\" .*`\r\n| regexp `.*\"(?P<website>https?://[^\"]+).*` \r\n| regexp `.*\" \\d+ (?P<size>\\d+) .*` \r\n| regexp `.*\" \\d+ (?P<response_time>\\d+\\.\\d+) .*`\r\n|~ \"HTTP/1.1 4\\\\d{2}\" \r\n|~ `$search`"
    }
   ]
  }
 ]
}